FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/* && rm -f /etc/nginx/conf.d/*
COPY demo/index.html /usr/share/nginx/html/index.html
RUN chmod -R 755 /usr/share/nginx/html
COPY nginx-demo.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
