FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY dashboard/index.html /usr/share/nginx/html/index.html
COPY nginx-dashboard.conf /etc/nginx/conf.d/default.conf
RUN chmod 644 /usr/share/nginx/html/index.html
