{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agentguard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentguard.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.apiHost }}
        {{- if .Values.dashboard.enabled }}
        - {{ .Values.ingress.dashboardHost }}
        {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agentguard.fullname" . }}-api
                port:
                  name: http
    {{- if .Values.dashboard.enabled }}
    - host: {{ .Values.ingress.dashboardHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agentguard.fullname" . }}-dashboard
                port:
                  name: http
    {{- end }}
{{- end }}
