{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentguard.fullname" . }}
  labels:
    {{- include "agentguard.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.postgresql.enabled) .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.licenseKey }}
  license-key: {{ .Values.secrets.licenseKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.adminKey }}
  admin-key: {{ .Values.secrets.adminKey | b64enc | quote }}
  {{- end }}
{{- end }}
