#!/bin/bash
set -e

# ── AgentGuard Self-Hosted Setup ─────────────────────────────────────────────
#
# Interactive setup script — generates a secure .env and starts AgentGuard.
# Usage: bash setup.sh
# Requirements: Docker + Docker Compose
# ─────────────────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo -e "${BLUE}${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}║  🔒  AgentGuard Self-Hosted Setup            ║${NC}"
echo -e "${BLUE}${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── Preflight checks ─────────────────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}✗ $1 is not installed.${NC}"
    echo -e "  Install it from: $2"
    exit 1
  fi
  echo -e "${GREEN}✓${NC} $1 found"
}

echo -e "${BOLD}Checking prerequisites...${NC}"
check_command docker  "https://docs.docker.com/get-docker/"
check_command curl    "https://curl.se/download.html"

# Check Docker Compose (v2 as plugin)
if docker compose version &>/dev/null 2>&1; then
  echo -e "${GREEN}✓${NC} docker compose found"
elif command -v docker-compose &>/dev/null; then
  echo -e "${YELLOW}⚠${NC}  docker-compose v1 found — recommend upgrading to Docker Compose v2"
  COMPOSE_CMD="docker-compose"
else
  echo -e "${RED}✗ Docker Compose not found.${NC}"
  echo -e "  Install it: https://docs.docker.com/compose/install/"
  exit 1
fi
COMPOSE_CMD="${COMPOSE_CMD:-docker compose}"

echo ""

# ── Generate secure PG password ───────────────────────────────────────────────

generate_password() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 24
  elif command -v python3 &>/dev/null; then
    python3 -c "import secrets; print(secrets.token_hex(24))"
  else
    # Fallback: urandom via od
    od -vAn -N24 -tx1 /dev/urandom | tr -d ' \n'
    echo
  fi
}

PG_PASSWORD=$(generate_password)
echo -e "${GREEN}✓${NC} Generated secure database password"

# ── License key (optional) ────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}License Key ${DIM}(optional)${NC}${BOLD}:${NC}"
echo -e "  ${DIM}Free tier: 25,000 events/month, 3 agents — no key needed${NC}"
echo -e "  ${DIM}Get a Pro key at: https://agentguard.tech/pricing${NC}"
echo ""
read -r -p "$(echo -e "Enter your license key ${DIM}[leave blank for Free tier]${NC}: ")" LICENSE_KEY

if [[ -n "$LICENSE_KEY" ]]; then
  if [[ "$LICENSE_KEY" =~ ^AGKEY- ]]; then
    echo -e "${GREEN}✓${NC} License key accepted"
  else
    echo -e "${YELLOW}⚠${NC}  Key doesn't start with 'AGKEY-' — continuing anyway (will be validated on startup)"
  fi
else
  echo -e "${DIM}  → Starting with Free tier limits${NC}"
fi

# ── Write .env ────────────────────────────────────────────────────────────────

ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo ""
  read -r -p "$(echo -e "${YELLOW}⚠${NC}  .env already exists. Overwrite? [y/N] ")" OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo -e "${DIM}  → Keeping existing .env${NC}"
  else
    WRITE_ENV=true
  fi
else
  WRITE_ENV=true
fi

if [[ "$WRITE_ENV" == "true" ]]; then
  cat > "$ENV_FILE" <<EOF
# AgentGuard Self-Hosted — generated by setup.sh
# $(date -u '+%Y-%m-%d %H:%M:%S UTC')

AGENTGUARD_LICENSE_KEY=${LICENSE_KEY}
PG_PASSWORD=${PG_PASSWORD}
EOF
  echo -e "${GREEN}✓${NC} Created .env"
fi

# ── Pull images ───────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Pulling Docker images...${NC}"
cd "$SCRIPT_DIR"
$COMPOSE_CMD pull

# ── Start services ────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Starting AgentGuard...${NC}"
$COMPOSE_CMD up -d

# ── Wait for healthy ──────────────────────────────────────────────────────────

echo ""
echo -e "${DIM}Waiting for services to become healthy...${NC}"

MAX_WAIT=120
WAIT=0
HEALTHY=false

while [[ $WAIT -lt $MAX_WAIT ]]; do
  STATUS=$(curl -sf http://localhost:8080/health 2>/dev/null || true)
  if echo "$STATUS" | grep -q '"status":"ok"'; then
    HEALTHY=true
    break
  fi
  printf "."
  sleep 3
  WAIT=$((WAIT + 3))
done

echo ""

if [[ "$HEALTHY" == "true" ]]; then
  echo ""
  echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}${BOLD}║  ✅  AgentGuard is running!                  ║${NC}"
  echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${BOLD}Dashboard:${NC}  ${CYAN}http://localhost:8080${NC}"
  echo -e "  ${BOLD}API:${NC}        ${CYAN}http://localhost:8080/api/v1${NC}"
  echo -e "  ${BOLD}Health:${NC}     ${CYAN}http://localhost:8080/health${NC}"
  echo ""
  if [[ -z "$LICENSE_KEY" ]]; then
    echo -e "  ${YELLOW}📊 Running on Free tier${NC} — 25,000 events/month"
    echo -e "  ${DIM}Upgrade at: https://agentguard.tech/pricing${NC}"
  else
    echo -e "  ${GREEN}🔑 License key active${NC}"
  fi
  echo ""
  echo -e "${DIM}  Logs: docker compose logs -f agentguard${NC}"
  echo -e "${DIM}  Stop: docker compose down${NC}"
  echo ""
else
  echo -e "${RED}${BOLD}✗ AgentGuard did not become healthy within ${MAX_WAIT}s${NC}"
  echo ""
  echo -e "Check logs for errors:"
  echo -e "  ${CYAN}docker compose logs agentguard${NC}"
  echo -e "  ${CYAN}docker compose logs postgres${NC}"
  echo ""
  exit 1
fi
